name: Publish docs

on:
  push:
    branches:
      - main
      - issue-54/feature/documentation

permissions:
  id-token: write
  pages: write

jobs:
  publish-docs:
    name: Publish docs
    runs-on: ubuntu-latest
    steps:     
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
      - uses: actions/checkout@v2
      - name: Build and publish
        run: |
          uv run sphinx-build docs/source docs/build/html
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/build/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4