name: Build and publish

on:
  workflow_run:
    workflows: ["Push to dev or main"]
    types:
      - completed

jobs:
  build-and-publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          uv build
          uv publish